### ISSUE TITLE
Blockchain error after restarting kubernetes nodes

### ISSUE THREAD

**Issue by deanzaka** [IBM-Blockchain/ibm-blockchain.github.io#67]
I was following the instruction from here https://ibm-blockchain.github.io/setup/ to setup blockchain on kubernetes cluster. The setup was successful.

But, after I tried to reboot the node in kubernetes cluster, the orderer failed to restart, as shown below:
<img width="1280" alt="screen shot 2018-01-18 at 12 08 16" src="https://user-images.githubusercontent.com/5698173/35081728-6ac8cff6-fc48-11e7-84cc-7a79875bdb8e.png">
<img width="1280" alt="screen shot 2018-01-18 at 12 14 46" src="https://user-images.githubusercontent.com/5698173/35081895-43274742-fc49-11e7-9892-a380f057d4de.png">

**Comment by mrshah-at-work** [comment]
@deanzaka can you let us know if you are using free cluster on IBM Container Service? Looks like the persistent storage where the bootstrap files for the orderer are stored didn't survive the reboot. We can replay the scenario and let you know how it goes.

**Comment by deanzaka** [comment]
@mrshah-at-ibm yes, we are using free cluster on IBM Container Service.
Thanks for your help, please let us know if there are any updates.

**Comment by deanzaka** [comment]
hi @mrshah-at-ibm, do you have any update on this issue?

**Comment by mrshah-at-work** [comment]
I do not have any update yet. We will give it a try this week. Sorry for the delay.

**Comment by deanzaka** [comment]
Yea, no worries. Thanks a lot guys.

**Comment by mrshah-at-work** [comment]
We found one of the issues (https://github.com/IBM-Blockchain/ibm-container-service/issues/61) but it might not be the one causing this. We will still need to continue testing.

**Comment by deanzaka** [comment]
Oh, yea, I actually notice that too. If we delete the pods then the kube deployments create it again, after that we still can query the data but can't invoke any transaction because we lost world state and the business network somehow. I wasn't sure if it's an expected behavior, but I leave it for now.

It'll be great if we can solve both of those problems in one solution.
I'll keep troubleshooting this issue from my side too. Thanks guys.

**Comment by mrshah-at-work** [comment]
@deanzaka I have not been able to replay the scenario, but afaik the "Reload" will reload the OS on the worker node, which will wipe the locally mounted file system data folders.. And thus, the orderer will not have stuff to start - this stuff is generated by the `utils` pod.

I hope this helps.

**Comment by dhyey20** [comment]
@deanzaka based on some tests that we ran, if the pod gets restarted (i.e. either you scale the deployment down to 0 and then up to 1, or somehow restart the container) the peer/orderer lose the ledger data, as mentioned in [issue](https://github.com/IBM-Blockchain/ibm-container-service/issues/61). But there is no error. 

But the case where someone tries to restart the kubernetes-worker node, using `bx cs worker-reboot <cluster-name> <worker-name>` in free cluster, the storage gets wiped out. So after restart the `/shared` folder is blank. This is because we are mounting the `/tmp` folder on the host to `/shared` on the containers. Investigating further to see if this can be solved (tracked [here](https://github.com/IBM-Blockchain/ibm-container-service/issues/66)).

**Comment by dhyey20** [comment]
This issue has been fixed with https://github.com/IBM-Blockchain/ibm-container-service/issues/67. Feel free to reopen if you still see problems. 

(please pull the latest code and try again)
